from tilaus import Tilaus
from asiakas import Asiakas

ASIAKAS = Asiakas.__name__.lower()
A_FIELDS = list(Asiakas.__dataclass_fields__.keys())
A_ID = A_FIELDS[0]
A_NIMI = A_FIELDS[1]
A_SPOSTI = A_FIELDS[2]
TILAUS = Tilaus.__name__.lower()
T_FIELDS = list(Tilaus.__dataclass_fields__.keys())
T_ID = T_FIELDS[0]
T_AS_ID = T_FIELDS[1]
T_SUMMA = T_FIELDS[2]
CREATE_ASIAKAS = f"CREATE TABLE IF NOT EXISTS {ASIAKAS} ({A_ID} INTEGER PRIMARY KEY AUTOINCREMENT, {A_NIMI} TEXT, {A_SPOSTI} TEXT)"
CREATE_TILAUS = f"CREATE TABLE IF NOT EXISTS {TILAUS} ({T_ID} INTEGER PRIMARY KEY AUTOINCREMENT, {T_AS_ID} INTEGER, {T_SUMMA} REAL)"
SELECT_TILAUSET = f"SELECT * FROM {TILAUS}"
SELECT_ASIAKKAAT = f"SELECT * FROM {ASIAKAS}"
SELECT_TILAUSET_ASIAKKAAT = f"SELECT * FROM {TILAUS} JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID}"
SELECT_TILAUSET_ASIAKKAAT_LEFT = f"SELECT * FROM {TILAUS} LEFT JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID}"
SELECT_TILAUSET_ASIAKKAAT_RIGHT = f"SELECT * FROM {TILAUS} RIGHT JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID}"
SELECT_TILAUSET_ASIAKKAAT_FULL = f"SELECT * FROM {TILAUS} FULL OUTER JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID}"
SELECT_TILAUSET_ASIAKKAAT_WHERE = f"SELECT * FROM {TILAUS} JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID} WHERE {TILAUS}.{T_SUMMA} > ?"
SELECT_TILAUSET_ASIAKKAAT_ORDER = f"SELECT * FROM {TILAUS} JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID} ORDER BY {TILAUS}.{T_SUMMA} DESC"
SELECT_TILAUSET_ASIAKKAAT_GROUP = f"SELECT SUM({T_SUMMA}), {ASIAKAS}.{A_NIMI} FROM {TILAUS} JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID} GROUP BY {TILAUS}.{T_AS_ID}, {ASIAKAS}.{A_NIMI}"
SELECT_TILAUSET_ASIAKKAAT_SUBQUERY = f"SELECT * FROM {TILAUS} JOIN {ASIAKAS} ON {TILAUS}.{T_AS_ID} = {ASIAKAS}.{A_ID} WHERE {TILAUS}.{T_SUMMA} > (SELECT AVG({T_SUMMA}) FROM {TILAUS})"
INSERT_TILAUS = f"INSERT INTO {TILAUS} ({T_AS_ID}, {T_SUMMA}) VALUES (?, ?)"
INSERT_ASIAKAS = f"INSERT INTO {ASIAKAS} ({A_NIMI}, {A_SPOSTI}) VALUES (?, ?)"
UPDATE_TILAUS = f"UPDATE {TILAUS} SET {T_AS_ID} = ?, {T_SUMMA} = ? WHERE {T_ID} = ?"
UPDATE_ASIAKAS = f"UPDATE {ASIAKAS} SET {A_NIMI} = ?, {A_SPOSTI} = ? WHERE {A_ID} = ?"
DELETE_TILAUS = f"DELETE FROM {TILAUS} WHERE {T_ID} = ?"
DELETE_ASIAKAS = f"DELETE FROM {ASIAKAS} WHERE {A_ID} = ?"
DELETE_TILAUS_BY_ASIAKAS = f"DELETE FROM {TILAUS} WHERE {T_AS_ID} = ?"
UPDATE_TILAUS_SET_NULL_BY_ASIAKAS = f"UPDATE {TILAUS} SET {T_AS_ID} = NULL WHERE {T_AS_ID} = ?"
CHECK_ASIAKAS_EXISTS = f"SELECT {A_ID} FROM {ASIAKAS} WHERE {A_ID} = ?"